language: node_js
node_js:
- "stable"
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database travis_myDiary;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
script: 
  - npm test
  
after_success: npm run coverage

